//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentSetUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string BuildingName { get; set; }
        public int RoomNumber { get; set; }
        public int Price { get; set; }
        public Nullable<int> Occupant1 { get; set; }
        public Nullable<int> Occupant2 { get; set; }
        public Nullable<int> Occupant3 { get; set; }
        public Nullable<int> Occupant4 { get; set; }
    }
}
